import { ToolRegistry } from "./registry.js";

import unitySceneTools from "./tools/unity/scene.js";
import unityGameObjectTools from "./tools/unity/gameobject.js";
import unityMaterialTools from "./tools/unity/material.js";
import unityScriptTools from "./tools/unity/script.js";
import unityAnimationTools from "./tools/unity/animation.js";
import unityPhysicsTools from "./tools/unity/physics.js";
import unityUITools from "./tools/unity/ui.js";
import unityLightingTools from "./tools/unity/lighting.js";
import unityCameraTools from "./tools/unity/camera.js";
import unityPrefabTools from "./tools/unity/prefab.js";
import unityAudioTools from "./tools/unity/audio.js";
import unityTerrainTools from "./tools/unity/terrain.js";
import unityNavmeshTools from "./tools/unity/navmesh.js";
import unityVFXTools from "./tools/unity/vfx.js";
import unityOptimizationTools from "./tools/unity/optimization.js";
import unityBuildTools from "./tools/unity/build.js";
import unityPlaytestTools from "./tools/unity/playtest.js";
import unityInputTools from "./tools/unity/input.js";
import unityTemplateTools from "./tools/unity/template.js";
import unityWeatherTools from "./tools/unity/weather.js";
import unityTimelineTools from "./tools/unity/timeline.js";
import unityMLAgentsTools from "./tools/unity/ml-agents.js";
import unityProBuilderTools from "./tools/unity/probuilder.js";
import unityPackageManagerTools from "./tools/unity/package-manager.js";
import unityScriptableObjectTools from "./tools/unity/scriptable-object.js";
import unityProfilerTools from "./tools/unity/profiler.js";
import unityGOAPTools from "./tools/unity/goap.js";
import unityRuntimeTools from "./tools/unity/runtime.js";
import unityAdvancedAudioTools from "./tools/unity/advanced-audio.js";
import unityVrcPerformanceTools from "./tools/unity/vrc-performance.js";
import unityVRChatSdkTools from "./tools/unity/vrchat-sdk.js";
import unityPhysBoneTools from "./tools/unity/physbone.js";
import unityModularAvatarTools from "./tools/unity/modular-avatar.js";
import unityFaceEmoTools from "./tools/unity/faceemo.js";
import unityTextureEditTools from "./tools/unity/texture-edit.js";
import blenderObjectTools from "./tools/blender/object.js";
import blenderMeshTools from "./tools/blender/mesh.js";
import blenderMaterialTools from "./tools/blender/material.js";
import blenderBakeTools from "./tools/blender/bake.js";
import blenderBatchTools from "./tools/blender/batch.js";
import blenderGameAssetTools from "./tools/blender/game_asset.js";
import blenderInspectionTools from "./tools/blender/inspection.js";
import blenderMeshRepairTools from "./tools/blender/mesh_repair.js";
import blenderProceduralTools from "./tools/blender/procedural.js";
import blenderCollectionTools from "./tools/blender/collection.js";
import blenderMeshAdvancedTools from "./tools/blender/mesh_advanced.js";
import blenderAnimationAdvancedTools from "./tools/blender/animation_advanced.js";
import blenderArmatureAdvancedTools from "./tools/blender/armature_advanced.js";
import blenderModifierExtendedTools from "./tools/blender/modifier_extended.js";
import blenderUvAdvancedTools from "./tools/blender/uv_advanced.js";
import blenderMaterialAdvancedTools from "./tools/blender/material_advanced.js";
import blenderAccessoryTools from "./tools/blender/accessory.js";
import blenderAvatarTools from "./tools/blender/avatar.js";
import blenderBodyShapeTools from "./tools/blender/body_shape.js";
import blenderClothFittingTools from "./tools/blender/cloth_fitting.js";
import blenderShapeKeyTools from "./tools/blender/shape_key.js";
import blenderWeightPaintTools from "./tools/blender/weight_paint.js";
import blenderVrmExportTools from "./tools/blender/vrm_export.js";
import blenderPolyhavenTools from "./tools/blender/polyhaven.js";
import blenderSketchfabTools from "./tools/blender/sketchfab.js";
import blenderPythonExecTools from "./tools/blender/python_exec.js";
import blenderHunyuan3dTools from "./tools/blender/hunyuan3d.js";
import godotNodeTools from "./tools/godot/node.js";
import godotResourceTools from "./tools/godot/resource.js";
import versionControlToolDefs from "./tools/system/version-control.js";
import transactionToolDefs from "./tools/system/transaction.js";
import pipelineToolDefs from "./tools/system/pipeline.js";
import recipeToolDefs from "./tools/system/recipe.js";
import safetyToolDefs from "./tools/system/safety.js";
import extensionToolDefs from "./tools/system/extension.js";
import assetGenerationToolDefs from "./tools/system/asset-generation.js";
import gameStudiosToolDefs from "./tools/system/game-studios.js";

export function registerAllTools(registry: ToolRegistry): void {
  // Unity tools
  registry.registerTools(unitySceneTools);
  registry.registerTools(unityGameObjectTools);
  registry.registerTools(unityMaterialTools);
  registry.registerTools(unityScriptTools);
  registry.registerTools(unityAnimationTools);
  registry.registerTools(unityPhysicsTools);
  registry.registerTools(unityUITools);
  registry.registerTools(unityLightingTools);
  registry.registerTools(unityCameraTools);
  registry.registerTools(unityPrefabTools);
  registry.registerTools(unityAudioTools);
  registry.registerTools(unityTerrainTools);
  registry.registerTools(unityNavmeshTools);
  registry.registerTools(unityVFXTools);
  registry.registerTools(unityOptimizationTools);
  registry.registerTools(unityBuildTools);
  registry.registerTools(unityPlaytestTools);
  registry.registerTools(unityInputTools);
  registry.registerTools(unityTemplateTools);
  registry.registerTools(unityWeatherTools);
  registry.registerTools(unityTimelineTools);
  registry.registerTools(unityMLAgentsTools);
  registry.registerTools(unityProBuilderTools);
  registry.registerTools(unityPackageManagerTools);
  registry.registerTools(unityScriptableObjectTools);
  registry.registerTools(unityProfilerTools);
  registry.registerTools(unityGOAPTools);
  registry.registerTools(unityRuntimeTools);
  registry.registerTools(unityAdvancedAudioTools);
  registry.registerTools(unityVrcPerformanceTools);
  registry.registerTools(unityVRChatSdkTools);
  registry.registerTools(unityPhysBoneTools);
  registry.registerTools(unityModularAvatarTools);
  registry.registerTools(unityFaceEmoTools);
  registry.registerTools(unityTextureEditTools);

  // Blender tools
  registry.registerTools(blenderObjectTools);
  registry.registerTools(blenderMeshTools);
  registry.registerTools(blenderMaterialTools);
  registry.registerTools(blenderBakeTools);
  registry.registerTools(blenderBatchTools);
  registry.registerTools(blenderGameAssetTools);
  registry.registerTools(blenderInspectionTools);
  registry.registerTools(blenderMeshRepairTools);
  registry.registerTools(blenderProceduralTools);
  registry.registerTools(blenderCollectionTools);
  registry.registerTools(blenderMeshAdvancedTools);
  registry.registerTools(blenderAnimationAdvancedTools);
  registry.registerTools(blenderArmatureAdvancedTools);
  registry.registerTools(blenderModifierExtendedTools);
  registry.registerTools(blenderUvAdvancedTools);
  registry.registerTools(blenderMaterialAdvancedTools);
  registry.registerTools(blenderAccessoryTools);
  registry.registerTools(blenderAvatarTools);
  registry.registerTools(blenderBodyShapeTools);
  registry.registerTools(blenderClothFittingTools);
  registry.registerTools(blenderShapeKeyTools);
  registry.registerTools(blenderWeightPaintTools);
  registry.registerTools(blenderVrmExportTools);
  registry.registerTools(blenderPolyhavenTools);
  registry.registerTools(blenderSketchfabTools);
  registry.registerTools(blenderPythonExecTools);
  registry.registerTools(blenderHunyuan3dTools);

  // Godot tools
  registry.registerTools(godotNodeTools);
  registry.registerTools(godotResourceTools);

  // System tools
  registry.registerTools(versionControlToolDefs);
  registry.registerTools(transactionToolDefs);
  registry.registerTools(pipelineToolDefs);
  registry.registerTools(recipeToolDefs);
  registry.registerTools(safetyToolDefs);
  registry.registerTools(extensionToolDefs);
  registry.registerTools(assetGenerationToolDefs);
  registry.registerTools(gameStudiosToolDefs);
}
