import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    'intro',
    'sitemap',
    {
      type: 'category',
      label: '準備 (はじめての方)',
      items: [
        'setup/prerequisites/node-install',
        'setup/prerequisites/unity-install',
        'setup/prerequisites/blender-install',
        'setup/prerequisites/godot-install',
        'setup/prerequisites/terminal-basics',
      ],
    },
    {
      type: 'category',
      label: 'インストール',
      items: [
        'setup/install',
        'setup/unity',
        'setup/blender',
        'setup/godot',
        'setup/verify-connection',
        {
          type: 'category',
          label: 'AIクライアント別セットアップ',
          items: [
            'setup/clients/claude-desktop',
            'setup/clients/cursor',
            'setup/clients/vscode',
            'setup/clients/claude-code',
            'setup/clients/gemini-cli',
            'setup/clients/lm-studio',
            'setup/clients/ollama',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'チュートリアル',
      items: [
        'tutorials/first-steps',
        'tutorials/scene-building',
        'tutorials/modeling',
        'tutorials/cross-app',
        'tutorials/save-restore',
        'tutorials/vrchat',
        'tutorials/physics-playground',
        'tutorials/avatar-editing',
        'tutorials/ai-playtest',
        'tutorials/animation-basics',
        'tutorials/lighting-scene',
        'tutorials/terrain-world',
        'tutorials/ui-design',
        'tutorials/sound-design',
        'tutorials/version-control-advanced',
      ],
    },
    {
      type: 'category',
      label: 'VRChat',
      items: [
        'vrchat/getting-started-vrchat',
        'vrchat/overview',
        'vrchat/world-creation',
        'vrchat/avatar-setup',
        'vrchat/outfit-change',
        'vrchat/expressions',
        'vrchat/physbone',
        'vrchat/texture-editing',
        'vrchat/optimization',
        'vrchat/upload',
        'vrchat/recipes',
      ],
    },
    {
      type: 'category',
      label: '上級チュートリアル',
      items: [
        'tutorials/advanced/custom-pipeline',
        'tutorials/advanced/goap-ai-system',
        'tutorials/advanced/shader-workflow',
        'tutorials/advanced/multiplayer-setup',
        'tutorials/advanced/performance-optimization',
        'tutorials/advanced/game-studios-workflow',
      ],
    },
    {
      type: 'category',
      label: '使い方',
      items: [
        'usage/basic-commands',
        'usage/unity-usage',
        'usage/blender-usage',
        'usage/godot-usage',
        'usage/vrchat-usage',
        'usage/tips-tricks',
      ],
    },
    {
      type: 'category',
      label: 'ガイド',
      items: [
        'guides/student-free',
      ],
    },
    {
      type: 'category',
      label: '仕組み',
      items: [
        'advanced/architecture',
        'advanced/modes',
        'advanced/http-api',
        'advanced/recipe',
        'advanced/local-llm',
        'advanced/multi-agent',
        'advanced/pipeline-detail',
        'advanced/game-studios',
        'advanced/philosophy',
      ],
    },
  ],
  referenceSidebar: [
    'reference/tool-explorer',
    'reference/unity-tools',
    'reference/blender-tools',
    'reference/godot-tools',
    'reference/system-tools',
    'reference/faq',
    'reference/changelog',
    {
      type: 'category',
      label: '開発に参加する',
      items: [
        'contributing/overview',
        'contributing/add-unity-tool',
        'contributing/add-blender-tool',
        'contributing/add-godot-tool',
        'contributing/project-structure',
      ],
    },
  ],
};

export default sidebars;
